[versions]
kotlin = "1.9.0"
agp = "8.12.0"
kotlin-latest = "2.3.0-RC2"
coroutines-build = "1.8.1"
coroutines-latest = "1.10.2"
jackson = "2.19.2"
androidx-test = "1.7.0"

[libraries]
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
shadow-gradle-plugin = { group = "com.gradleup.shadow", name = "com.gradleup.shadow.gradle.plugin", version = "9.2.2" }
asm-utils = { group = "org.ow2.asm", name = "asm-util", version = "9.9" }
dalvik-dx = { group = "com.jakewharton.android.repackaged", name = "dalvik-dx", version = "16.0.1" }
androidx-test-runner = { group = "androidx.test", name = "runner", version = "1.5.2" }
kotlin-logging-jvm = { group = "io.github.oshai", name = "kotlin-logging-jvm", version = "7.0.0" }
kotlin-gradle-plugin-api = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin-api", version = "1.7.0" }
byte-buddy-agent = { group = "net.bytebuddy", name = "byte-buddy-agent", version = "1.18.2" }
ktor-io-jvm = { group = "io.ktor", name = "ktor-io-jvm", version = "2.0.1" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version = "1.3.15" }
junit5-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version = "5.10.3" }
junit4 = { group = "junit", name = "junit", version = "4.13.2" }
kotlinx-coroutines-core-build = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines-build" }
kotlinx-coroutines-jdk8-build = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-jdk8", version.ref = "coroutines-build" }
kotlinx-coroutines-jdk8-latest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-jdk8", version.ref = "coroutines-latest" }
kotlinx-coroutines-debug-build = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-debug", version.ref = "coroutines-build" }
kotlinx-coroutines-debug-latest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-debug", version.ref = "coroutines-latest" }
multidex = { group = "androidx.multidex", name = "multidex", version = "2.0.1" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson" }
jackson-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
kotlin-metadata-jvm = { group = "dev.reformator.kotlin-metadata-jvm-repack", name = "kotlin-metadata-jvm-repack", version = "0.9.0-3" }
retrace = { group = "com.guardsquare", name = "proguard-retrace", version = "7.8.1" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-test" }
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "androidx-test" }

[plugins]
shadow = { id = "com.gradleup.shadow" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
android-library = { id = "com.android.library" }
nmcp-aggregation = { id = "com.gradleup.nmcp.aggregation", version = "1.3.0" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
#noinspection SimilarGradleDependency
kotlin-jvm-build = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
#noinspection SimilarGradleDependency
kotlin-jvm-latest = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-latest" }
android-application-version = { id = "com.android.application", version.ref = "agp" }
compose-multiplatform-latest = { id = "org.jetbrains.compose", version = "1.10.0-beta02" }
compose-compiler-latest = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-latest" }
kotlin-multiplatform-latest = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-latest" }
android-application = { id = "com.android.application" }
